# Netlify konfigūracija projektui

[build]
  command = "npm run fast-build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://siemka-design-tool.netlify.app"
  NODE_OPTIONS = "--max-http-header-size=16384"
  # Išvengiame URL problemų, užtikrinant, kad serverio pusėje būtų tinkamos URL nuorodos
  NEXT_PUBLIC_VERCEL_URL = "https://siemka-design-tool.netlify.app"
  NEXT_TELEMETRY_DISABLED = "1"
  # Pagreitinimas
  NEXT_IGNORE_ESM_CACHE = "true"
  NEXT_DISABLE_SOURCEMAPS = "true"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"
  
  [plugins.inputs]
  include = [
    ".next/cache/**",
    "node_modules/.cache/**"
  ]

# Naudojame lokalų optimizavimo plėtinį
[[plugins]]
  package = "/opt/build/repo/netlify/plugins/nextjs-optimizer"

# Pridedame serverio funkcijų konfigūraciją
[functions]
  node_bundler = "esbuild"
  included_files = ["**/*.ts"]
  
# Pridedame persiuntimo taisykles API užklausoms
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Pridedame cache antraštes
[[headers]]
  for = "/*"
  
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-maxage=31536000, immutable"