[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://siemka-design-tool.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200